# Generated by Django 2.2.10 on 2021-04-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_divisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=250)),
                ('distrik_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Distrik')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20)),
                ('nip', models.CharField(max_length=20)),
                ('nama_pegawai', models.CharField(max_length=225)),
                ('tgl_masuk', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tgl_lahir', models.DateField()),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Divisi')),
                ('nama_toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Toko')),
            ],
        ),
    ]
