# Generated by Django 2.2.10 on 2021-04-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_jabatan_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='divisi',
        ),
        migrations.DeleteModel(
            name='Divisi',
        ),
    ]
