# Generated by Django 2.2.10 on 2021-04-14 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210414_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Jabatan'),
        ),
    ]
