# Generated by Django 2.2.10 on 2021-04-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_buyer', models.CharField(max_length=125)),
                ('aktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dept', models.CharField(max_length=5)),
                ('nama_dept', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_Grup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_dept_grup', models.CharField(max_length=5)),
                ('nama_dept_grup', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mclass', models.CharField(max_length=4)),
                ('nama_mclass', models.CharField(max_length=225)),
                ('kode_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('konversi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Merk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_merk', models.CharField(max_length=4)),
                ('merk', models.CharField(max_length=50)),
                ('margin', models.IntegerField()),
                ('kode_mclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MClass')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=125)),
                ('aktif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('barcode', models.IntegerField()),
                ('sku_desc', models.CharField(max_length=225)),
                ('harga_jual', models.IntegerField()),
                ('harga_beli', models.IntegerField()),
                ('harga_beli_besar', models.IntegerField()),
                ('hpp', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('article', models.CharField(max_length=50)),
                ('sku_aktif', models.BooleanField()),
                ('sku_flag', models.BooleanField()),
                ('diskon', models.IntegerField()),
                ('mulai_diskon', models.DateField()),
                ('akhir_diskon', models.DateField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept')),
                ('mclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MClass')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Merk')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Size')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='merk',
            name='kode_supp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Supplier'),
        ),
        migrations.AddField(
            model_name='merk',
            name='nama_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Buyer'),
        ),
        migrations.AddField(
            model_name='dept',
            name='kode_dept_grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept_Grup'),
        ),
    ]
