# Generated by Django 2.2.10 on 2021-04-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210416_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='barcode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.BigIntegerField(),
        ),
    ]
