# Generated by Django 2.2.10 on 2021-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210419_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='harga_beli_besar',
            field=models.BigIntegerField(),
        ),
    ]
